import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyAppBar from "@/components/navBar";
import AppProvider from "./Alternative";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "P.E.I",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <MyAppBar />
          {children}
          <div dir='rtl'>
            <Footer />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
