import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Vazirmatn } from 'next/font/google'
import AppProvider from './Alternative'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'P.E.I',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><AppProvider>{children}</AppProvider></body>
    </html>
  )
}
